### ISSUE TITLE
Copy dll files using CMake?

### ISSUE THREAD

**Issue by jakobrobert** [tals/audacity-noise-reduction#15]
Windows expects the dll files for libsndfile to be in the same directory as the executable, linking the lib alone is not sufficient. Therefore, in #12 I have copied the dll files using the batch file.

In my opinion, this is a bit hacky. Do you know, if there is a more elegant way by copying files to the build directory using CMake? This scenario should not be that uncommon, because e.g. in a game you also would have to copy the assets like images, audio files to the build directory.

**Comment by tals** [comment]
You can use https://cmake.org/cmake/help/latest/command/file.html#copy

**Comment by tals** [comment]
Fixed by #16
