### ISSUE TITLE
compile error： fatal error: 'sndfile.h' file not found

### ISSUE THREAD

**Issue by ChokJohn** [tals/audacity-noise-reduction#4]
clang++ -MT .o/noisereduction/main.o -MD -MP -MF .d/noisereduction/main.Td -std=c++11 -Wall -Wextra -pedantic -DNDEBUG -Ofast -c -o .o/noisereduction/main.o noisereduction/main.cpp
In file included from noisereduction/main.cpp:2:
noisereduction/NoiseReduction.h:10:10: fatal error: 'sndfile.h' file not found
#include <sndfile.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [Makefile:115: .o/noisereduction/main.o] Error 1

**Comment by tals** [comment]
Install sndfile :)

on mac its `brew install libsndfile`

**Comment by tals** [comment]
Added instructions to the readme. Let me know if this this works for you!
