### ISSUE TITLE
Provide interface to use buffers instead of files

### ISSUE THREAD

**Issue by jakobrobert** [tals/audacity-noise-reduction#5]
I think it would be very useful to be able to pass audio buffers as float vectors to the profileNoise and reduceNoise methods instead of loading a track from a file.

For my purposes I required this type of interface and I have adjusted the NoiseReduction class accordingly.

I would like to integrate my changes by integrating my versions of the profileNoise and reduceNoise in addition to the existing ones.

If you agree, let me know.

**Comment by tals** [comment]
Yeah that makes a lot of sense.
There's a bunch of low hanging fruits to improve the ergonomics and performance of this library, so these improvements are very welcome :)

What is your plan for the time-based indexing it is currently using?
I think the ergonomics of it are worth keeping.

**Comment by jakobrobert** [comment]
In my code, I have just removed the time indices. ProfileNoise and ReduceNoise receive separate buffers, one which only includes noise and one which contains the buffer from which the noise should be removed.

So it is called like this:
noiseReduction.ProfileNoise(noiseBuffer);
outputBuffer = noiseReduction.ReduceNoise(inputBuffer);

How about if I just add my version of the NoiseReduction class as an additional class and then we look further how we can integrate it?

**Comment by tals** [comment]
I can see that working if NoiseReductionWorker remains shared, since that holds the guts of the process which you dont want to duplicate.

Did you just patch `InputTrack` so that it accepts a float*, instead of working with an `SndContext` , or did you change it buffers all the way down?

**Comment by jakobrobert** [comment]
The first, I did not change NoiseReductionWorker at all. And I changed InputTrack and OutputTrack to work with vector of float directly (not float*, I do not like C-style arrays :D), so they do not have any dependency to sndfile.

So probably the most flexible approach would be to create a common superclass / interface for two track implementations, a track from file and a track from buffer. Then to NoiseReduction worker, it does not matter how the track is created, it can use both in the same way.

So you would have the superclass InputTrack, two subclasses BufferedInputTrack and FileInputTrack, similarly for OutputTrack.

**Comment by tals** [comment]
Got it!
The main problem with it is that you still need two NoiseReduction implementations to go with the two tracks implementations, which I don't love.

Working with buffers (like you are doing) does sound more correct than a file, since a lot of applications will already have the data in-memory.

What about making the buffers API be main API, and pulling out the file stuff so it's more a helper function or something, and have them just read to the buffer?
That way theres just one *Track, one NoiseReduction etc.

**Comment by jakobrobert** [comment]
Yeah, this is a great idea.

But I guess in this way you could not stream the data from a file, but have to read it in at once. But if the file is not gigabytes large, this should be no issue.

I will try it out in the next days and create a pull request 😀

**Comment by tals** [comment]
You're right on the streaming thing. I think the current code does a reasonable job at it.
Hmmm.

Maybe make the main API be callback-based, and similarly to the SndFile implementation, add a helper for working with simple buffers

**Comment by iooops** [comment]
@Jack-42 
Hi I also need this feature. 
It would be great if you could share your code if you don't mind so that I don't need to do that again.

**Comment by jakobrobert** [comment]
@iooops Hey, sorry, I was busy the last days, I think i can push the code on monday :)

**Comment by iooops** [comment]
@Jack-42 Thanks!!!

**Comment by jakobrobert** [comment]
@iooops Hey, sorry, I got some more stuff to do for university. But on Wednesday / Thursday I should finally get it done 😀

**Comment by jakobrobert** [comment]
@iooops I got some problems getting the project running so it will take more time. See #6

**Comment by tals** [comment]
@Jack-42 should be taken care of. lmk if this helps

**Comment by jakobrobert** [comment]
> 
> 
> @Jack-42 should be taken care of. lmk if this helps

Yes, with clang it works, thank you very much :)
I did not even know that clang is available for Linux :D

Btw, while testing I realized a segmentation fault occurs if you specify an invalid input filename.

**Comment by jakobrobert** [comment]
@tals One question, what is the purpose of NoiseReductionWorker::StartNewTrack()? In the method ProcessOne() where it is called, it says in the comment:
```
/**
* Frames coming from libsndfile are striped, channel-wise: [{left, right},  {left, right}, ...]
* NR code works on a per-track basis
*/
```
But when I look into the method StartNewTrack(), the comment does not really make sense to me, because it does not refer to the channel count at all.

**Comment by tals** [comment]
haha it really doesn't make sense in that context! I think I was doing some code massaging and messed it up. It was 3 years ago so my memory is a little fuzzy 😅

**Comment by jakobrobert** [comment]
@tals Sometimes I do not understand the compiler :D I had to change the version to C++14 so that it can find std::make_unique, but the problem only appeared in a new file I created. In the existing files , e.g. NoiseReduction.cpp it was used and this compiled without any problem.

**Comment by jakobrobert** [comment]
@tals Do you know how ProfileNoise actually deals with multiple channels? I can see that it iterates through the channels and processes each individually. But there is only one statistics object and it seems to store each statistic only once, not for each channel. Are the different channels somehow averaged?

**Comment by tals** [comment]
> @tals Do you know how ProfileNoise actually deals with multiple channels? I can see that it iterates through the channels and processes each individually. But there is only one statistics object and it seems to store each statistic only once, not for each channel. Are the different channels somehow averaged?

Hmm that does sound suspicious. Audacity (which this is a port of) seem to do this too:
https://github.com/audacity/audacity/blob/master/src/effects/NoiseReduction.cpp#L698

I see a few possibilities here:
- the original code is wrong and this hurts the NR in Audacity too.
- the original code is "wrong" but it isn't triggered somehow (maybe they do funny things like run the Effects worker on each track separately?)
- it somehow performs **better** than doing it per channel

**Comment by tals** [comment]
Good job :)
