### ISSUE TITLE
Extend CLI for new buffer based API

### ISSUE THREAD

**Issue by jakobrobert** [tals/audacity-noise-reduction#8]
I think with the new buffer based API (see pull request #7) it would also be useful to extend the command line interface (CLI).

My suggestion is to add an optional parameter --profile for the case that the noise signal required for profiling is contained in a separate track rather than being part of the input track. In this case, the time indices t0 and t1 should be ignored.

So you should be able to execute the app as follows:

`./bin/noisereduction_driver --input signal_with_noise.wav --profile noise.wav --output signal_clean.wav`

If you think this is useful, let me know, I can implement it :)

**Comment by tals** [comment]
that sounds useful. go for it :)
